# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Netsec"
license = "MIT"
licenselink = "https://github.com/BenjaminBurton/BenjaminBurton.github.io/blob/main/themes/netsec/LICENSE"
description = ""
homepage = "https://benjaminburton.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Lavell Burton"
  homepage = "https://benjaminburton.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
